### ISSUE TITLE
[REQUEST] Wine ReWire to Jack Audio, like WineAsio.

### ISSUE THREAD

**Issue by juanpc2018** [wineasio/wineasio#105]
PropellerHeads created [ReWire](https://en.wikipedia.org/wiki/ReWire_(software_protocol))
similar concept to Jack, but works like an Audio Input Plugin in the DAW "ProTools, etc..."

ReBirth 338 v2.01 works in [Linux / Wine](https://ubuntuforums.org/showthread.php?t=846551)
but there is No ReWire tp JackAudio for Linux...

it would require a JackPlugin with 18 outputs or more, if using Reason + MTC.

**Comment by falkTX** [comment]
please dont create the same issue in multiple places.

ReWire is quite the different thing from ASIO, and it is a discontinued protocol/product anyway.
