### ISSUE TITLE
Unable to open a JACK client

### ISSUE THREAD

**Issue by riccardocagnasso** [wineasio/wineasio#12]
```
cannot open DB environment: Resource temporarily unavailable
Cannot create thread res = 11
Cannot start Jack client listener
Cannot start channel
JackShmReadWritePtr1::~JackShmReadWritePtr1 - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Unable to open a JACK client as: FL64
BDB0126 mmap: Resource temporarily unavailable
cannot open DB environment: Resource temporarily unavailable
Cannot create thread res = 11
Cannot start Jack client listener
Cannot start channel
JackShmReadWritePtr1::~JackShmReadWritePtr1 - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Unable to open a JACK client as: FL64
```

Every wineasio application I try, gets this. Which usually makes the whole application crash.

Of course jack is running, e.g.:

```
Cannot lock down 107341338 byte memory area (Cannot allocate memory)
>>> Warning. Could not set higher priority for a SCHED_OTHER process using setpriority().
Cannot use real-time scheduling (RR/5) (1: Operation not permitted)
JackClient::AcquireSelfRealTime error
>>> Recording to "jack_capture_01.wav". Press <Return> or <Ctrl-C> to stop.
>>> Please wait while writing all data to disk. (shouldn't take long) 
   |"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""|
00:|                                                                 |
01:|                                                                 |
Buffer: 4.01s./4.01s    Time: 0.09m.   DHP: [ ]  Overruns: 0  Xruns: 0
Finished.
```

**Comment by riccardocagnasso** [comment]
Actually setting correct realtime privileges fixed it. Maybe should be mentioned in the doc?

**Comment by norz3n** [comment]
> Actually setting correct realtime privileges fixed it. Maybe should be mentioned in the doc?

I want to ask how you did it, I am now trying to run WineASIO with Ableton Live 10 Suite, but I get the same error, I want to know more about realtime privileges

**Comment by riccardocagnasso** [comment]
> > Actually setting correct realtime privileges fixed it. Maybe should be mentioned in the doc?
> 
> I want to ask how you did it, I am now trying to run WineASIO with Ableton Live 10 Suite, but I get the same error, I want to know more about realtime privileges

Well I'm running archlinux and actually there's a package for that 

`    ~  pacman -Ss realtime | grep privileges                            ✔ 
community/realtime-privileges 3-1 (pro-audio realtime) [installed]
    Realtime privileges for users
`

If you are on some other distro, you can probably look at the arch package and replicate it. It's just some system configuration.

**Comment by falkTX** [comment]
I am closing this ticket since it is not directly wineasio's issue, but a system level thing.
