### ISSUE TITLE
ALSA support

### ISSUE THREAD

**Issue by jarkkojs** [wineasio/wineasio#13]
I wonder how difficult it would to have optional direct ALSA support? I don't really need my mixers audio interface for my Ubuntu desktop and would not mind Wine takeover. Also, I run at most only a single audio application at a time under wine. To summarize, JACK is only overhead in this kind of situation.

I could give it shot possibly but would need some feedback whether this is technically feasible or not at first.

**Comment by falkTX** [comment]
Feasible? sure, if you have enough time and dedication.
It will not be within the WineASIO project though, but feel free to fork and do whatever, it is all open-source.

The best would be to have it as an official wine driver, but due to licensing this is not possible.
