### ISSUE TITLE
makefile errors

### ISSUE THREAD

**Issue by hsully03** [wineasio/wineasio#16]
Can't build 32 or 64 bit verison on Arch. Here is the full make log.
`make build ARCH=i386 M=32
make[1]: Entering directory '/home/user/wineasio'
make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.  Stop.
make[1]: Leaving directory '/home/user/wineasio'
make: *** [Makefile:15: 32] Error 2`

Any ideas of why this could be happening?

**Comment by falkTX** [comment]
yes, you need to initialize the git submodules.

**Comment by hsully03** [comment]
> yes, you need to initialize the git submodules.

Yep, that was the issue. Cloning the submodules into the repo fixed it. There's probably a way to clone the submodules with the main repo at the same time I'm just not sure how.

**Comment by falkTX** [comment]
yes, use `git clone --recursive ...`
