### ISSUE TITLE
wine-staging

### ISSUE THREAD

**Issue by sfjuocekr** [wineasio/wineasio#28]
Hey,

I'm trying to build wineasio for the winehq-staging branch, this builds fine after some minor include modifications but the build only gives me the "wineasio.dll.so" file and if I put that into /opt/wine-staging/lib/wine/i386-unix/wineasio.dll.so it won't work.

My guess is that /opt/wine-staging/lib/wine/i386-windows/wineasio.dll needs to be build as well, but Im not sure how to do that right now.

These are the two includes needed for winehq-staging:

INCLUDE_PATH         += -I/opt/wine-staging/include
INCLUDE_PATH         += -I/opt/wine-staging/include/wine/windows

I'm building this on Ubuntu 21.04 with the winehq-staging ppa, my goal was to try pw-jack to see if this would work or maybe add PipeWire support to wineasio.

Guess I have some reading up to do, but if you know how to generate both the dll and the dll.so that would be a great start!

**Comment by Retidurc** [comment]
related to #24 and https://github.com/wineasio/wineasio/issues/24#issuecomment-832203638 I think
