### ISSUE TITLE
wine-vanilla 6.14 regsvr32 fails to see the wineasio.dll

### ISSUE THREAD

**Issue by rugubara** [wineasio/wineasio#29]
I built wineasio and installed it into the path, where all wine *.dll.so are located - in my Gentoo distribution they are /usr/{lib,lib64}/wine-vanilla-6.14/wine/x86_{32,64}-unix"

The command wine64 regsvr32 wineasio.dll returns ```regsvr32: Failed to load DLL 'wineasio.dll'```.
Setting WINEPATH to /usr/lib64/wine-vanilla-6.14/wine/x86_64-unix doesn't help. 

putting full path to the regsvr32 does the trick and the dll gets registered. wineasio shows up in the application (Ableton) but I can't choose it. The error comes up failed to open audio device WineASIO driver.

**Comment by rugubara** [comment]
Important to note, I tried to build wineasio-1.0.0

**Comment by rugubara** [comment]
The moment when I try to switch to WineASIO, the Ableton spits out:
```
0024:err:ole:apartment_add_dll couldn't load in-process dll L"wineasio.dll"
0024:err:ole:com_get_class_object no class object {48d0c522-bfcc-45cc-8b84-17f25f33e6e8} could be created for context 0x1
```

**Comment by mickski56** [comment]
See #24, basically you need to build the dll as well as the "dll.so" library
