### ISSUE TITLE
Can't build for x86_64 architecture

### ISSUE THREAD

**Issue by mani-rai** [wineasio/wineasio#32]
I use manjaro. Build for 32 bit works flawlessly, but having trouble for 64 bit. I am getting the following error:

> winegcc -shared -m64 -mnocygwin wineasio.dll.spec -L/usr/lib64/wine -L/usr/lib/wine -L/usr/lib/x86_64-linux-gnu/wine -L/usr/lib/x86_64-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib64 -L/opt/wine-stable/lib64/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib64 -L/opt/wine-staging/lib64/wine -o build64/wineasio.dll.so build64/asio.c.o build64/main.c.o build64/regsvr.c.o   -ljack   -lodbc32 -lole32 -lwinmm -luuid
> ld: relocatable linking with relocations from format elf32-i386 (/usr/local/lib/wine/libuuid.a(uuid.o)) to format elf64-x86-64 (wineasio.buBJMa.o) is not supported
> winebuild: ld failed with status 1
> winegcc: winebuild failed
> make[1]: *** [Makefile.mk:109: build64/wineasio.dll.so] Error 2
> make[1]: Leaving directory '/tmp/wineasio'
> make: *** [Makefile:18: 64] Error 2
> 

I am kind of sure that I need to link to 64 bit wine, but not sure how. I tried giving library path as followings:

> make -e LIBRARY_PATH=/usr/lib/wine 64

But this gives the following error:

> winegcc -shared -m64 -mnocygwin wineasio.dll.spec -L/usr/lib64/wine -L/usr/lib/wine -L/usr/lib/x86_64-linux-gnu/wine -L/usr/lib/x86_64-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib64 -L/opt/wine-stable/lib64/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib64 -L/opt/wine-staging/lib64/wine -o build64/wineasio.dll.so build64/asio.c.o build64/main.c.o build64/regsvr.c.o  /usr/lib/wine -ljack   -lodbc32 -lole32 -lwinmm -luuid
> winegcc: File does not exist: /usr/lib/wine
> make[1]: *** [Makefile.mk:109: build64/wineasio.dll.so] Error 2
> make[1]: Leaving directory '/tmp/wineasio'
> make: *** [Makefile:18: 64] Error 2

**Comment by EduApps-CDG** [comment]
Same
