### ISSUE TITLE
wineasio 1.1.0 upgrade breaks certain Windows hosts that runs on wine-staging 6.4

### ISSUE THREAD

**Issue by JosteinAndersen** [wineasio/wineasio#33]
Hi,

Wineasio was upgraded to 1.1.0 yesterday and now, hosts such as Superior Drummer SOLO and Garritan Aria Player can't be used with it. SOLO sees the ASIO driver but complains about a Windows WX problem (..wx/ctrlsubh: assert "!Items.Is.Emty()" failed in wxitemContainer::InsertItems():need something to insert)  and the Aria Player does not see the ASIO at all. The plugins work fine in Carla.

I have now downgraded to 1.0.0 and pinned it (sudo apt-mark hold wineasio=5:1.0.0-1kxstudio1), everything is ok again.

My system: Kubuntu-20.04 (with KXStudio repos enabled) and wine-staging-6.4.

Jostein

**Comment by AVLinux** [comment]
Wine-Staging 6.6 broke WineASIO 1.0.0 and WineASIO 1.1.0 was released as a fix for systems with Wine-Staging 6.6+ but it is not perfected yet either and needs some file linking and copying to work properly..

Things are in a weird spot now where 2 versions of WineASIO are needed for the either side of the Wine-Staging breaking point at 6.6. It appears as though the Wine devs don't really plan on changing anything on their end and have introduced a requirement for 'fakedlls' to be present on the system which has caused the breakage in WineASIO..

Bug #24 has the gory details

**Comment by falkTX** [comment]
Yeah the details are all on #24, which is pretty much resolved now afaik.
Closing this one as duplicate then.
