### ISSUE TITLE
fatal error: jack/jack.h

### ISSUE THREAD

**Issue by samueljholiver** [wineasio/wineasio#38]
make build ARCH=x86_64 M=64
make[1]: Entrando no diretório '/home/sam/Downloads/wineasio-1.0.0'

Package jack was not found in the pkg-config search path.
Perhaps you should add the directory containing `jack.pc'
to the PKG_CONFIG_PATH environment variable
Package 'jack', required by 'virtual:world', not found
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows    -m64 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration  -DNATIVE_INT64 -O2 -DNDEBUG -fvisibility=hidden -o build64/asio.c.o asio.c
asio.c:33:10: fatal error: jack/jack.h: Arquivo ou diretório inexistente
   33 | #include <jack/jack.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:98: build64/asio.c.o] Erro 1
make[1]: Saindo do diretório '/home/sam/Downloads/wineasio-1.0.0'

make: *** [Makefile:18: 64] Erro 2

**Comment by KottV** [comment]
it wants jack devel files

**Comment by laurentdebricon** [comment]
sudo apt install libjack-jackd2-dev

**Comment by falkTX** [comment]
Yep, make sure to install jack development packages before building.
