### ISSUE TITLE
Apps crash when ASIO device is selected

### ISSUE THREAD

**Issue by ChuckDaniels87** [wineasio/wineasio#4]
* System: _Archlinux_
* Wine: _5.4_
* Jack2: _1.9.14_

Applications running on Wine crash when Jack is running and the ASIO device is selected. However, they do not crash when Jack is not running.

Debug information of the crash: https://gist.github.com/ChuckDaniels87/a1ec8da7829033076d573c6c17f43079

Things I have tried without success:
* Downgrade to Wine 4.0.
* Use the current `wineasio` AUR version 
* Use the version of `wineasio` in this repo.
* Reinstall applications.
* Test in a clean Wine prefix.

Notes:
* This setup was working fine about a year ago when it broke without any known changes in my configuration.
* More information can be found in #3 since the discussion started there. However, this seems a different bug.
* I am using Pulseadio bridge too if this information is relevant for something.
* Additional information of a glibc bug that is possibly related:
  * Ubuntu Ticket - https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1757517
  * Related comment - https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1757517/comments/2

**Comment by ChuckDaniels87** [comment]
Should I copy this issue to [wineasio/wineasio](https://github.com/wineasio/wineasio) repo or you will migrate them?

**Comment by falkTX** [comment]
I will rename that repo in order to keep history of this one intact. but in a few days not now. no need to do something from your side, yet

**Comment by CCF100** [comment]
@ChuckDaniels87 Any luck?

**Comment by ChuckDaniels87** [comment]
No luck sorry. I will try to take a look this weekend again.

@falkTX would be great to have some tips to debug this problem. What is your usual workflow to debug issues of wineasio and wine apps in general?

**Comment by ismaelgv** [comment]
It seems that my wine prefix had no access to `/usr/lib/wine/wineasio.dll.so` inside wine. This did not entirely fix my problem but at least is not crashing now.

**Comment by gusix** [comment]
This seems very Arch specific, it crashes on both my computers with completely unrelated hardware using every wineasio versions/repos I could find. Last time I checked, it was working fine, but maybe 1 or 2 years ago.

**Comment by devmpv** [comment]
I'm experiencing same issue with Manjaro and it was completely fine on OpenSUSE Tumbleweed. Can't get any error that would lead to some clues. Also tried multiple repo's and builds.

**Comment by falkTX** [comment]
one previous issue was due to a mis-installation of jack2 and lib32-jack2 of archlinux.
can you verify that they match exactly?

**Comment by devmpv** [comment]
@falkTX Thanks a lot! It appears that manjaro have installed "jack" package by default. So i just installed "jack2" and "lib32-jack2" packages with manager and it removes "jack" automatically. (For those who will try - do not remove jack first, just install jack2 to keep all dependencies)
Everything is working fine with wine 5.9 from system repo. Will try lutris version later on.

**Comment by gusix** [comment]
I checked it a couple times already, but I did it again just to be sure, I reinstalled wine main/staging, jack/jack2 rebuilding wineasio with every change, I just don't understand, isnt there anything I can try to get more details on the crash ?
 [Log from guitar rig](https://pastebin.com/MjJ7LQg7)

**Comment by falkTX** [comment]
Did you try updating/reinstall lib32-jack2 package as well?
That is the crucial thing here.

**Comment by gusix** [comment]
Yes, I did, I will report it on arch's side since it looks like a packaging issue.
Thanks for your help anyway

**Comment by kangoo2097** [comment]
I am not hundred percent sure, if the issues I had are related to this. I am also running Arch and had issues with wineasio with the ASIO client crashing when the wineasio device was selected. The error messages that I got looked similar to the guitar rig log @gusix posted. 

I could make wineasio work by installing the `realtime-privileges` package and adding my user account to the `realtime` group. (See also https://wiki.archlinux.org/index.php/Realtime_process_management#Configuring_PAM). Until now, I did only test with a manually compiled wineasio from this repository, but this works so far for me.

**Comment by ismaelgv** [comment]
> I could make wineasio work by installing the realtime-privileges package and adding my user account to the realtime group. 

I can confirm that @kangoo2097 solution fixed my issue in Arch, thank you so much!

I have also compiled wineasio manually from this repo.

**Comment by ismaelgv** [comment]
I have just adopted the wineasio AUR package. I will try to update it and apply these fixes as soon as possible.

**Comment by ismaelgv** [comment]
I have updated the AUR package and updated its dependencies. This issue should be fixed now for Arch Linux users. If there is any problem just contact me.
