### ISSUE TITLE
JACK not available in wincfg Audio with Wine 7

### ISSUE THREAD

**Issue by lobneroO** [wineasio/wineasio#42]
I'm using Arch Linux. I installed wine 7 and wine-mono yesterday from the official repositories and I tried to install wineasio (from the AUR, but I later also build it myself). The AUR comes with the 32bit and 64bit wineasio.dll.so but no wineasio.dll (within the /usr/lib64/wine and /usr/lib32/wine folders anyway). I got these wineasio.dll.sos to register successufully, but when I then open winecfg and try to choose JACK in the audio tab, in all options it just shows me PulseAudio. The same for wine-staging, which I also tried.

When building from source, I got the wineasio.dll.so files as well as the wineasio.dll files. I copied those to their respective /usr/libXY/wine directories and registered them, but no luck with that either.

I tried to just open an ML Sound Lab free amp as well as Cockos Reaper, but while both give me the ASIO option, neither of them shows an actual device afterwards (and give me errors of not finding any). Jack is started of course (although I cannot say that I'm sure to have it set up correctly, but it works for native programs).

Has wineasio been tested for wine 7 by anyone yet? 

I'm new to this, so I don't really know what to look for for debugging. If I can produce any log files that might be of help, please let me know how to do so.

**Comment by falkTX** [comment]
wineasio only works for asio, not winecfg

**Comment by lobneroO** [comment]
I see. I read somewhere that I was supposed to set it up there.
However I then wold still have a problem not being able to use JACK/wineasio within my programs. Do I have to set something else up (besides registering the wineasio.dll files)?

**Comment by falkTX** [comment]
typically that is enough, just make sure to use wine64 for 64bit registration, and set the wineprefix before hand if needed

**Comment by lobneroO** [comment]
okay, thanks for your help. i uninstalled wine, wine-mono and deleted the usr/libXY/wine folders as well as the ~/.wine prefix . i also cloned the rtaudio submodule (rather than just copying include/asio.h into the empty folder) and rebuild it, reinstalled wine and wine-mono and copied the dll files. i then only registered the .dll files (not the .so files) and now it works.

I'm not sure exactly what was the problem before, but I assume I destroyed my wine installation by all the back and forth with the different wine versions and different wineasio.dll.so versions
