### ISSUE TITLE
Can't load ASIO driver error using WineASIO on Fedora

### ISSUE THREAD

**Issue by chefexperte** [wineasio/wineasio#45]
I have been trying to set up wineasio on my device so I could use FL without big latency, but when I try to select WineASIO as the audio device I get an error and I can't use it. 
The error I am getting: "**Couldn't open the ASIO driver**"

I am trying to run: FL Studio 20 with WineASIO built from GitHub source on Lutris 0.5.9.1 on my Fedora 35
I am using wine 7.2
The JACK server seems to be running (shows running on QJackCtl).

However I do not get any output on the log when I try to open WineASIO in FL, however I see output when I select FL ASIO. 

I have the following audio related packages: 
alsa-firmware
alsa-lib
pipewire-alsa
wine-alsa
pipewire-jack-audio-connection-kit
pipewire-libs
pipewire-pulseaudio
qjackctl
wireplumber
(few more but I don't think those are relevant)

I have not have had anything to do with those audio packages or anything before, so I do not know which logs or information exactly is needed to resolve this problem, so if anything is missing I can provide that, I just don't know what. 
I have had a look at the other issues, I don't think mine is one of the other open ones, at least the resolutions I have tried did not work.

**Comment by falkTX** [comment]
wineasio is not compatible with pipewire, you need to use real jack for now.

**Comment by chefexperte** [comment]
In order to use the real JACK, which components that are not compatible with it do I have to replace? 
From what I understood I can't use pipewire if I want to use WineASIO with JACK, right? So would I have to replace pipewire and wireplumber?

**Comment by falkTX** [comment]
You should ask this on a fedora user support forum. I do not know.

**Comment by mxdpeep** [comment]
https://discussion.fedoraproject.org/t/patrickl-pipewire-wineasio/31890

*Filip Oščádal*
*https://mxd.cz <https://mxd.cz>*
