### ISSUE TITLE
make 32 error - tried to mod Makefile.mk , reinstalled libjack2_0 - errors/warnings still persist

### ISSUE THREAD

**Issue by succeedmr123** [wineasio/wineasio#47]
Dear,

I try to compile WineASIO 1.1.0  on;  

- 64-bit platform (Ubuntu-Studio 20.04.4 LTS), 
- multiarch is enabled, there is a proper
- Wine 7.5 wine-devel installed i.e. development version

I pulled github repo with rt audio successfully via 

`cd /wineasio/
git submodule update --init --recursive`

Wine-devel dirs seem to be necessary to add to Makeconfig.mk.
After some modifications where necessary to add missing wine-devel includes in makefile.mk

I entered the local git wineasio dir and started compilation

make 32 on initially brought some warnings, e.g.  like 

`asio.c:438:13: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘LONG’ {aka ‘long int’} [-Wformat=]
  438 |         ERR("Unable to allocate IOChannel structures for %i channels\n", This->wineasio_number_inputs);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                              |
      |                                                                              LONG {aka long int}
`

Trying to working around this, I reinstalled libjack library by issuing:

`sudo apt reinstall libjack-jackd2-0 `
...
long story short:

last error I can not get past in make32 is this one; ld linker search for libjack i386 ver failed

That is, basically, a part of the make 32 output,  near the end of the full output ->

`...
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libjack.so when searching for -ljack
/usr/bin/ld: cannot find -ljack
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
...`

Full commandline and output was:

`❯ make 32
make build ARCH=i386 M=32
make[1]: Entering directory '/home/user/repos/git/wineasio'
winegcc build32/asio.c.o build32/main.c.o build32/regsvr.c.o -shared -m32 -mnocygwin wineasio.dll.spec -L/usr/lib32/wine -L/usr/lib/wine -L/usr/lib/i386-linux-gnu/wine -L/usr/lib/i386-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib32 -L/opt/wine-stable/lib32/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib32 -L/opt/wine-staging/lib32/wine -ljack \
	-lodbc32 -lole32 -lwinmm -luuid -o build32/wineasio.dll.so
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libjack.so when searching for -ljack
/usr/bin/ld: cannot find -ljack
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make[1]: *** [Makefile.mk:116: build32/wineasio.dll.so] Error 2
make[1]: Leaving directory '/home/user/repos/git/wineasio'
make: *** [Makefile:15: 32] Error 2`

In contrast, make64 compiles without any issue and produces the correct output.

Upon researching at the inet there are even some hints that Ubuntu (unknown version) does not have full 32 bit libs libs support, and that chroot/container compiling would do the trick.

In any way, this was a showstopper for now.

It would be great to have a method for make 32 to be compile locally without any error.

Am willing to try things out for this system and wine-devel variant, make it work and feed back the results here

Thanks in advance

System:
Ubuntu-Studio 20.04.1 Ubuntu SMP PREEMPT x86_64

**Comment by falkTX** [comment]
This has nothing to do with wineasio, but something in your system.
For linking a program, you need to have the devel libs installed. On debian/ubuntu this would be libjack-jackd2-dev, but due to how debian does this, you can't have both libjack-jackd2-dev:i386 and libjack-jackd2-dev:amd64 installed at the same time.

An alternative is to just manually create the needed system dev lib yourself, something like...
```
cd /usr/lib/i386-linux-gnu/
sudo ln -s libjack.so.0 libjack.so
```
