### ISSUE TITLE
Regsvr32: Failed to load DLL 'wineasio' | Arch Linux; Plasma KDE

### ISSUE THREAD

**Issue by shard77** [wineasio/wineasio#50]
Hey, I successfully installed wineasio and both 32 and 64bit DLL's are correctly installed in my libraries. 

![image](https://user-images.githubusercontent.com/106669955/175817799-e72fbaf7-6ecd-46fa-b3ba-79bcf9a4f8b6.png)

Any toughts? Thanks!

**Comment by satyam-bhardwaj** [comment]
Run this command instead, as suggested by yay during installation. `wine64 regsvr32 /usr/lib/wine/x86_64-windows/wineasio.dll`
