### ISSUE TITLE
Workaround for crashes with pipewire-jack?

### ISSUE THREAD

**Issue by begin-theadventure** [wineasio/wineasio#56]
This fork apparently fixes PipeWire crashes: https://github.com/TobiasKozel/wineasio.
Would it be possible to merge it?

There's also this: https://github.com/BWagener/wineasio, which has some compilation fixes (?).

**Comment by falkTX** [comment]
The pipewire hack is a very nasty one that has no place on the official repo.
And I believe issue has already been resolved in latest pipewire anyway.

**Comment by begin-theadventure** [comment]
Thanks for the quick response :)
