### ISSUE TITLE
Possible to use without JACK?

### ISSUE THREAD

**Issue by probonopd** [wineasio/wineasio#63]
Would it be possible to use this without JACK (e.g., FreeBSD OSS or ALSA)?
My use case is that JACK is way too cumbersome to set up, never works without configuration ("plug and play"), and adds extra complexity. I would be willing to sacrifice a bit of latency for true "plug and play".

**Comment by falkTX** [comment]
no, this tool was made specifically to allow the usage of JACK within wine.
just stick with regular pulseaudio drivers on wine if you dont care for latency.
