### ISSUE TITLE
Cannot make it work in a 32bit wine prefix

### ISSUE THREAD

**Issue by ciolansteen** [wineasio/wineasio#7]
Hi, just tested with a 32bit only wine prefix. Trying to select asio stops doing nothing. The 64bit prefix works fine btw. 

Distro - Arch Linux

The wine versions i tested with: 5.0 staging, 5.6 staging, 5.8 staging. For each i compiled using that specific wine version. In all situations, dll registers successfully.  

i registered using

32bit
```
WINEPREFIX=/path_to_32bit_wine_prefix/ WINEDLLPATH=/path_to_specific_wine_dir/lib32 /path_to_specific_bin_dir/wine regsvr32 wineasio.dll
```
64bit
```
WINEPREFIX=/path_to_64bit_wine_prefix/ WINEDLLPATH=/path_to_specific_wine_dir/lib64 /path_to_specific_bin_dir/wine64 regsvr32 wineasio.dll
```

Also, there's nothing in jack logs. Is there anything i can do to debug this?

**Comment by falkTX** [comment]
Do you have lib32-jack2 installed? If so, did you try to rebuild it? (it does not rebuild/update automatically, see #4)

32bit JACK clients need to work first, so that 32bit WineASIO can work as well.
See if you can get that to work first, then Wine stuff. Not sure the best place to find 32bit applications for ArchLinux though, you will have to find that yourself..

**Comment by ciolansteen** [comment]
Sorry, meanwhile I migrated to windows 10 due to too many issues on linux and limited time to fix them. I'll leave this issue open just in case anyone else faces the same problem and they may be able to test further.

**Comment by falkTX** [comment]
sure, I understand.
But I think the issue is also trying to use Windows-specific applications on Linux. Sometimes they work, sometimes they dont.
It is a much better choice to go native, Bitwig is somewhat similar to Live, so that might be an option for next time.

**Comment by falkTX** [comment]
Tested this on ArchLinux, it is working. There was a period where wine 6.5 broke everything, but afaik it works again.

The steps in the readme need to be done carefully, and adjusted for ArchLinux paths, but they work.

```
[vagrant@archlinux wineasio]$ sudo cp build64/wineasio.dll /usr/lib/wine/x86_64-windows/
[vagrant@archlinux wineasio]$ sudo cp build64/wineasio.dll.so /usr/lib/wine/x86_64-unix/
[vagrant@archlinux wineasio]$ sudo cp build32/wineasio.dll /usr/lib32/wine/i386-windows/
[vagrant@archlinux wineasio]$ sudo cp build32/wineasio.dll.so /usr/lib32/wine/i386-unix/
[vagrant@archlinux wineasio]$ regsvr32 /usr/lib32/wine/i386-windows/wineasio.dll 
wine: created the configuration directory '/home/vagrant/.wine'
002c:fixme:winediag:LdrInitializeThunk wine-staging 7.2 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
wine: configuration in L"/home/vagrant/.wine" has been updated.
regsvr32: Successfully registered DLL '/usr/lib32/wine/i386-windows/wineasio.dll'
[vagrant@archlinux wineasio]$ wine64 regsvr32 /usr/lib/wine/x86_64-windows/wineasio.dll 
regsvr32: Successfully registered DLL '/usr/lib/wine/x86_64-windows/wineasio.dll
```
