### ISSUE TITLE
JACK protocol mismatch (8 vs 9)

### ISSUE THREAD

**Issue by RaphaelNeubert** [wineasio/wineasio#71]
I've installed jack2 version 1.9.22 via gentoo's package manager portage.
After that, I compiled wineasio into a 32-bit dll. 

Once I started the jackd using qjackctl, I tried to use the wine application that uses wineasio.
Unfortunately, the jack server seems to reject any communication and throws the error:
`JACK protocol mismatch (8 vs 9)` where the 8 is referring to the clients jack protocol version and the 9 to the servers.

Jacks protocol version was bumped from 8 to 9 when version 1.9.19 was released (https://jackaudio.org/news/2021/07/16/jack2-v1919-release.html)

I guess that means that  wineasio is currently not compatible with any Jack version >= 1.9.19?

**Comment by falkTX** [comment]
this means your 32bit jack libs dont match your system jack libs, you need to update both

**Comment by RaphaelNeubert** [comment]
This is what i thought too but it seems like its using the correct system library.
```
ldd wineasio.dll.so:
 linux-gate.so.1 (0xf7f75000)
 libjack.so.0 => /usr/lib/libjack.so.0 (0xf7ecb000)
 libm.so.6 => /lib/libm.so.6 (0xf7dfd000)
 libc.so.6 => /lib/libc.so.6 (0xf7a00000)
 libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/32/libstdc++.so.6 (0xf7600000)
 libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/32/libgcc_s.so.1 (0xf7dd4000)
  /lib/ld-linux.so.2 (0xf7f77000)
```
```
ldd /usr/bin/jackd:
linux-vdso.so.1 (0x00007fff281f1000)
libjackserver.so.0 => /usr/lib64/libjackserver.so.0 (0x00007fa8d1d39000)
libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007fa8d1cec000)
libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6 (0x00007fa8d1a00000)
libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libgcc_s.so.1 (0x00007fa8d1cc8000)
libc.so.6 => /lib64/libc.so.6 (0x00007fa8d182e000)
libm.so.6 => /lib64/libm.so.6 (0x00007fa8d1756000)
/lib64/ld-linux-x86-64.so.2 (0x00007fa8d1e11000)
```
Inside `/usr/lib/` there is only one libjack.so and one libjackserver.so. The same is true for `/usr/lib64/`.
I can check the ownership of the so files using qfile:
```
qfile /usr/lib/libjack.so.0:
media-sound/jack2-1.9.22: /usr/lib/libjack.so.0 -> libjack.so.0.1.0
```
```
qfile -v /usr/lib64/libjackserver.so.0:
media-sound/jack2-1.9.22: /usr/lib64/libjackserver.so.0 -> libjackserver.so.0.1.0
```

As you can see the librarys that are getting used are both provided by jack2-1.9.22 which should use jack protocol version 9.

I uninstalled jack2 to see if the makefile is finding any other jacklib's but this is not the case. When jack2 is uninstalled the compilation fails.

**Comment by RaphaelNeubert** [comment]
I wanted to try to compile wineasio on a debian based machine using libjack-dev and copy the resulting .dll.so to my gentoo machine to see if that works but i couldn't do that because the newest jack version on mint is like 6 years old and is still using JACK protocol version 8.

Has anybody ever successfully used wineasio with a jack version > 1.9.19?

**Comment by falkTX** [comment]
protocol mismatch is not related to the API, the API set for jack (including jack1, jack2 and pipewire) is stable.

the issue for you is that the client side (libjack) does not match the server side (libjackserver and jackd). I assumed it was due to 32bit libs mismatching, but I guess your problem is likely to go deeper.

this is not an issue in wineasio, but with your setup. jack libs must always match the server, and yours dont somehow.
