### ISSUE TITLE
Freezing issue with FL Studio, and crashing with Ableton Live when selecting the WINEASIO option.

### ISSUE THREAD

**Issue by Naitrate** [wineasio/wineasio#74]
I'm having an issue with FL Studio (Which freezes) and Ableton (Which crashes) when using the COPR build from here: https://copr.fedorainfracloud.org/coprs/patrickl/pipewire-wineasio/

I tried adding my user to the jackuser, realtime, and audio groups. I've tried the wineasio-register script alongside manually copying files. Nothing that I've tried seemingly makes it not crash. I've even tried the PIPEWIRE_LATENCY environment variable to see if I could get it working, with no dice.

I'm using:
Fedora 39 Beta
wine-8.18.r0.ga5625909 ( TkG Staging Esync Fsync )
WineASIO 1.2.1
Pipewire and KDE Plasma (Wayland)

[wine_output.log](https://github.com/wineasio/wineasio/files/13199318/wine_output.log)
[wine_output_fl.log](https://github.com/wineasio/wineasio/files/13199320/wine_output_fl.log)

**Comment by falkTX** [comment]
did you try with real jack instead of pipewire yet? get things to work with jack, even if in dummy mode, then go for pipewire

**Comment by Naitrate** [comment]
Looks like running "winetricks sound=alsa" on each of the wine prefixes fixed the issue with FL Studio and VBASIOTest freezing when selecting the device (The VBASIOTest works fine, and FL Studio doesn't freeze but it complains about the bitrate), but Ableton Live still seemingly crashes with those changes.

I was able to get the FL Studio ASIO plugin working with both FL Studio and Ableton at least.

Figure I'll close this. Thanks for the suggestion though.

**Comment by deusnovus** [comment]
Were you able to choose an audio input/output on Ableton Live while on wine 8.18? A lot of people, including me, are getting a "Failed to launch audio device "Pulseaudio DX"" error and WineASIO is no different. I'm on Fedora 38 as well and I/O on Ableton Live 10/11 only works for me on wine-staging 8.4.

**Comment by illtellyoulater** [comment]
I had the exact same problem and finally sorted it out by using the WineASIO build @nicholastay shared at the beginning of his awesome guide. You can find it at https://nick.tay.blue/2024/01/06/wineasio/.

**Huge thanks to Nicholas !!!** 👍💥
