### ISSUE TITLE
No sound with WineASIO in fl studio

### ISSUE THREAD

**Issue by MiftikCZ** [wineasio/wineasio#80]
After hours of fixing my fl studio crashing when selecting wineasio as sound driver, i have finally fixed that and wineasio works well but i cant hear anything or cant record anything when i have wineasio selected - no errors, just silence.
Also with primary sound driver selected audio output works (and of course without microphone which is the reason im doing all this).

Arch linux up to date
- FL studio 21.0.3 Producer edition
- Using jack2, pipewire, alsa

here is my config in fl studio, let me know if i should post jack config or something
![image](https://github.com/wineasio/wineasio/assets/89579269/0cc00d3f-fe05-40e0-9179-7c5be30b0ab2)

thanks

**Comment by falkTX** [comment]
you are either using jack2 or pipewire, likely not both.

for pipewire check in some graph/patchbay tool if it connects to the right places

**Comment by MiftikCZ** [comment]
i have both installed, also i guess pipewire-jack doesn't work for wineasio so how can i fix the problem if im using jack2? i dont even know if my wineasio is pointed correctly, maybe that's the issue but i dont know how to fix it, i didnt find anything online

![obrazek](https://github.com/wineasio/wineasio/assets/89579269/65dfd71c-16d2-4ad5-a633-b71a331ed907)

**Comment by begin-theadventure** [comment]
I have installed `pipewire-jack` and `lib32-pipewire-jack` on Arch and they conflict with/provide jack2.
Try `Helvum` and `qpwgraph` for routing.

**Comment by MiftikCZ** [comment]
> I have installed `pipewire-jack` and `lib32-pipewire-jack` on Arch and they conflict with/provide jack2. Try `Helvum` and `qpwgraph` for routing.

i will try tomorrow but it already look like it could work thanks

**Comment by MiftikCZ** [comment]
I just saw that the problem may be that the jack2 doesn't produce any sound because of its driver set to `dummy` because i noticed that when i have `alsa` driver selected from `jack_control ds alsa`, it wont start and throws this error *(in qjackctl because the error in jack_control isnt telling that much)*. With `dummy` driver it starts normally but it doesn't produce any sound.

```
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
Released audio card Audio0
audio_reservation_finish
Cannot initialize driver
JackServer::Open failed with -1
Failed to open server
09:11:35.173 JACK byl zastaven
09:11:44.839 Nepodařilo se připojit k serveru JACK jako klient. - Celková operace se nezdařila. - Nelze se připojit k serveru. Další informace hledejte, prosím, v okně s hlášením.
Cannot connect to server socket err = Adresář nebo soubor neexistuje
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
```
Maybe this is more jack issue than wineasio but i guess it could help someone here

**Comment by MiftikCZ** [comment]
Update: i finally fixed it and now it works!!
So i just removed `jackdbus` so now just use
```
jackd -d alsa -d pipewire -p $PERIOD_SIZE -r $SAMPLE_RATE
``` 
whereas `$PERIOD_SIZE = 1024` and `$SAMPLE_RATE = 48000` in my case
source: https://github.com/wineasio/wineasio/issues/30#issue-976148574
