### ISSUE TITLE
Can't change sample rate for FL Studio, causes crash

### ISSUE THREAD

**Issue by irreducible-leaf** [wineasio/wineasio#83]
When I select WineASIO as the device in FL Studio audio settings, I get en error message saying

`The needed sample rate (44100 Hz) couldn't be set or is not supported by the ASIO driver. Please try another sample rate.` 

It seems it starts off at 48000 by default. But then the whole program crashes, so I can't click the "Show ASIO Panel" button to change the sample rate.

![image](https://github.com/wineasio/wineasio/assets/153296036/cb1959ab-d760-40a7-80ff-38815fec093a)

Is there some way I can set the sample rate externally, before starting FL Studio? Because otherwise I'm caught in this trap where it crashes before I can select the correct value.

**Comment by falkTX** [comment]
the sample rate comes from jack

**Comment by irreducible-leaf** [comment]
Thanks for that. However I no longer think the error is just due to the sample rate, as even if I change the FL project to have a 48kHz rate and then select WineASIO, I don't see the error

`The needed sample rate (44100 Hz) couldn't be set or is not supported by the ASIO driver. Please try another sample rate.`

but FL crashes anyway.

IDK if I should close this issue, or reopen another one, but I don't really have any details of why it's crashing to supply. The only logs say:

```
$ WINEPREFIX=~/.jackwine wine '/home/leaf/.jackwine/drive_c/Program Files/Image-Line/FL Studio 21/FL64.exe' 
0074:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0054:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000135
```

but they print out before the crash occurs.
