### ISSUE TITLE
rtaudio file empty 

### ISSUE THREAD

**Issue by 14kaitou** [wineasio/wineasio#9]
can't make 64 nor 32 the rtaudio file is empty 
output
 
`make build ARCH=x86_64 M=64
make[1]: Entering directory '/username/wine/wineasio'
make[1]: *** No rule to make target 'rtaudio/include/asio.h', needed by 'build'.  Stop.
make[1]: Leaving directory /'username/wine/wineasio'
make: *** [Makefile:18: 64] Error ` 

can somebody help me?

**Comment by falkTX** [comment]
clone with submodules enabled or grab the real tarball from https://github.com/wineasio/wineasio/releases
github does not handle submodules properly, so it is confusing at first..

**Comment by 14kaitou** [comment]
thank you

**Comment by Poikilos** [comment]
To clone with submodules enabled: `git clone --recurse-submodules https://github.com/wineasio/wineasio.git`
